# Nigtly is required for the specialization, const generic exprs, and portable SIMD.
# Once all are stabilized we can move to a stable toolchain
[toolchain]
channel = "nightly-2026-04-08"
components = ["rustfmt", "clippy"]
