name: CI

on:
  push:
    branches:
      - main
  pull_request: {}

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.92.0
  RUST_BACKTRACE: 1

jobs:
  build-test:
    name: Build and Test 🔬
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, aarch64]
        runner: [ubuntu-latest]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --verbose --all
      - name: Run tests
        run: cargo test

  check-spirv-kernel:
    name: Check SPIRV kernel is compiled
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Install `cargo-gpu`
        run: cargo install --git https://github.com/rust-gpu/cargo-gpu cargo-gpu
      - name: Compile the kernel
        run: |
          cargo gpu build \
            --shader-crate crates/kernels/vulkan-and-cpu \
            --auto-install-rust-toolchain
      - name: Check that the SPIRV hasn't changed
        run: |
          ls crates/kernels/vulkan-and-cpu/kernel.spv
          git diff --quiet --exit-code -- crates/kernels/vulkan-and-cpu/kernel.spv

  e2e:
    name: End to end tests
    strategy:
      fail-fast: false
      matrix:
        backend: [cpu, vulkan-cpu, vulkan]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Install Linux system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install \
            mesa-vulkan-drivers \
            libvulkan1 \
            vulkan-tools \
            vulkan-validationlayers \
            gdal-bin
          vulkaninfo
      - name: Run end to end tests
        run: ./benchmarks/run.sh ${{ matrix.backend }}

  lints:
    name: "Lints 💅"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: clippy,rustfmt
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-shear, cargo-msrv
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Clippy version
        run: cargo clippy --version
      - name: Lint
        run: cargo clippy -- --deny warnings
      - name: Formatting
        run: cargo fmt --check
      - name: Check for unused dependencies
        run: cargo shear

